[package]
name = "include-doc-macro"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
description = "Include examples in your Rustdocs."
keywords = ["documentation", "examples", "rustdoc"]
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true }
quote = { workspace = true }
proc-macro-error = { workspace = true }
ra_ap_syntax = { workspace = true }
itertools = { workspace = true }
proc-macro2 = { workspace = true }
